# Generated by Django 4.2.2 on 2023-08-06 10:34

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default='01-01-1990', validators=[user.models.validate_date_of_birth]),
        ),
    ]
