# Generated by Django 4.2.2 on 2023-08-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
    ]
