# Generated by Django 4.2.2 on 2023-07-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(upload_to='uploaded_files/%Y/%m/%d/'),
        ),
    ]
