# Generated by Django 4.2.2 on 2023-07-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_city', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('favorite_pizza', models.CharField(blank=True, max_length=255)),
                ('feedback_two', models.TextField(blank=True)),
            ],
        ),
    ]
