# Generated by Django 4.2.2 on 2023-07-29 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)])),
                ('favorite_city', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('favorite_pizza', models.CharField(blank=True, max_length=255)),
                ('feedback_two', models.TextField(blank=True)),
                ('do_you_like_hot_dogs', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
