# Generated by Django 4.2.2 on 2023-07-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='do_you_like_hot_dogs',
            new_name='tattoo',
        ),
    ]
