# Generated by Django 4.2.2 on 2023-07-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['name'], name='movie_name_index'),
        ),
    ]
