# Generated by Django 4.2.2 on 2023-07-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_remove_actor_first_name_remove_actor_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.AlterField(
            model_name='director',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
