# Generated by Django 4.2.2 on 2023-07-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_delete_actor_alter_director_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
    ]
