# Generated by Django 4.2.2 on 2023-07-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_remove_movie_director'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
    ]
