# Generated by Django 4.2.2 on 2023-07-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0017_rename_actor_movie_actors'),
    ]

    operations = [
    ]
