# Generated by Django 4.2.2 on 2023-07-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0018_auto_20230718_2008'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='actor',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_actor'),
        ),
    ]
