# Generated by Django 4.2.2 on 2023-07-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0019_actor_unique_actor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movie',
            new_name='movie_name_idx',
            old_name='movie_name_index',
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['slug'], name='slug_idx'),
        ),
    ]
