# Generated by Django 4.2.2 on 2023-07-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0020_rename_movie_name_index_movie_name_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='director',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_director'),
        ),
    ]
