# Generated by Django 4.2.2 on 2023-07-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0021_alter_actor_slug_alter_director_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='premiere_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
