# Generated by Django 4.2.2 on 2023-07-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0023_movie_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
