# Generated by Django 4.2.2 on 2023-07-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0024_movie_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='color',
            field=models.BooleanField(default=True),
        ),
    ]
